.TH reportbug-ng 1
.SH NAME
reportbug-ng \- Reports a bug to Debian's BTS.
.SH SYNOPSIS
.B reportbug-ng
.SH DESCRIPTION
.B reportbug-ng
is primarily designed to report bugs in the Debian distribution; by
default, it creates an email to the Debian bug tracking system at
.I submit@bugs.debian.org
with information about the bug you've found.
.SH OPTIONS
Reportbug-ng does currently ignore all options.
.SH AUTHOR
Bastian Venthur <venthur at debian org>.
