.TH reportbug-ng 1
.SH NAME
reportbug-ng \- Reports a bug to Debian's BTS.
.SH SYNOPSIS
.B reportbug-ng [package]
.SH DESCRIPTION
.B reportbug-ng
is primarily designed to report bugs in the Debian distribution; by
default, it creates an email to the Debian bug tracking system at
.I submit@bugs.debian.org
with information about the bug you've found.
.SH OPTIONS
Providing the package-parameter is equivalent to starting reportbug-ng,
entering something in the searchbar and pressing enter.
.SH AUTHOR
Bastian Venthur <venthur at debian org>.
