.TH REPORTBUG-NG "1" "April 2007" "reportbug-ng" "User Commands"
.SH NAME
reportbug-ng \- An easy to use alternative to reportbug.
.SH SYNOPSIS
reportbug\-ng [Package] [Option]
.SH DESCRIPTION
Report a bug in Debian's BTS.
.SS "options:"
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.SH HOMEPAGE
http://reportbug\-ng.alioth.debian.org
.SH COPYRIGHT
Copyright (C) 2007 Bastian Venthur <venthur at debian org>
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
